{
    startEdging();
    sendMessage('%LetTheEdgeFade%');
    sendMessage('This never gets old, does it..');
    sendMessage('No matter how many times you get yourself right there on the edge');
    sendMessage('Only for me to take your orgasm away from you');
    startEdging();
    sendMessage('%LetTheEdgeFade%');
    sendMessage('What are you now?');
    sendMessage('Just a helpless little edge puppet for me to use and destroy %Grin%');
    startEdging(2, 7);
    sendMessage('%LetTheEdgeFade%');
    sendMessage('You want me to continue, you want me to stop');
    sendMessage('All these different feeling clashing in your submissive mind right now');
    sendMessage('How can you ever be sure what you really want?');
    startEdging(2, 7);
    sendMessage('%LetTheEdgeFade%');
    sendMessage('Eventually you will learn that it doesn\'t matter what you want');
    sendMessage('It\'s what I want from you that matters');
    startEdging(2, 7);
    sendMessage('%LetTheEdgeFade%');
    sendMessage('The more you edge, the more you can feel your willpower erode and fade away');
    sendMessage('Until you\'re just a mindless goon, edging on command again and again');
    startEdging();
    sendMessage('%LetTheEdgeFade%');
    sendMessage('Is this what you\'re reduced to now?');
    sendMessage('A goon, a puppet, a toy?');
    sendMessage('There\'s nothing that you\'d rather be though, right?');
    sendMessage('You exactly where you belong');
    startEdging();
    sendMessage('And again...');
    startEdging();
    sendMessage('Over and over and over...');
    startEdging();
    sendMessage('Until your brain turns to a soft grey horny mush...');
    startEdging();
    sendMessage('%LetTheEdgeFade%');
    startEdging(2, 5);
}