{

    let answers = [
        'Make it feel good %SlaveName%',
        'Make that cock feel amazing',
        'Make that cock feel good',
        'Make that cock feel better than it\'s ever been',
        'Blow blow blow',
        'Just blow blow blow %Grin%',
        'Just blow for me',
        'Just blow for me %SlaveName%',
        'Keep blowing',
        'Keep blowing %SlaveName%',
        'Keep going',
        'Keep going just like that... good %SlaveName%',
        'Don\'t stop blowing',
        'Don\'t stop %SlaveName%, I want you even ' + 'more humiliated',
        'I know you can keep going for me, %SlaveName%',
        'You have no choice but to keep blowing for me',
        'Don\'t speed up or slow down, just keep going at this pace',
        'Slow down a little bit @StrokeSlower',
        'Slow down %SlaveName% @StrokeSlower',
        'Slow down your sucks for me @StrokeSlower',
        'Blow a little slower now @StrokeSlower',
        'Blow as slow as you can @StrokeSlowest',
        'Blow really slow now, until you can\'t go any slower @StrokeSlowest',
        'Speed up now %SlaveName% @StrokeFaster',
        'Speed up your sucks a little bit @StrokeFaster',
        'Blow a little faster @StrokeFaster',
        'Blow faster @StrokeFaster',
        'As fast as you can now! @StrokeFastest',
        'Go as fast as you can, but try not to let it slip out! @StrokeFastest',
        'Go a bit deeper',
        'Make sure to keep your teeth away from that cock',
        'When I see this, I just think of what is about to come %EmoteHappy% @ShowGayImage',
        'I love that you\'re doing this for me',
        'I love how much you\'re willing to degrade yourself for me',
        'It turns me on so much that you do this for me',
        'I\'m loving every second of this %Grin%',
        'I love making you ' + random('do this', 'blow') + ' for me',
        'It turns me on so much when you suffer for me',
        'Your suffering turns me on so much',
        'You have no idea how much I ' + random('enjoy', 'love') + ' seeing you suffer for me',
        'Nothing gets me hotter than making you my little submissive pet',
        'It makes me ' + random('wet', 'hot') + ' to know you\'d do anything for me, %SlaveName%',
        'I wish I could see you right now',
        'I\'m trying to picture you sitting there all covered in spit and tears %EmoteHappy%',
        'I want you submissive',
        'I want you suffering',
        'I want you to blow like never before',
        'Suffer for me',
        'I hope that cock is ' + random('pulsing', 'throbbing') + ' like crazy',
        'Humiliating you makes me feel so good',
        'I\'m gonna take all your pleasure for myself',
        'I\'m gonna take every last bit of your pleasure for myself',
        'Mmmm blow that cock for me %SlaveName%',
        'Show me how much you want to please me',
        'Humiliate yourself for my ' + random('enjoyment', 'pleasure'),
        'Blow for me',
        'Keep blowing for me',
        'Watch how every blow makes you ' + 'even more humiliated',
        'Let every blow make you ' + 'even more submissive',
        'Let your mouth slide up and down that blow',
        'Just switch off you brain and blow now',
        'I\'m going to make this so much worse on you',
        'That soreness isn\'t going to get any better',
        'That\'s you @ShowGayImage',
        'That\'s what you will be soon @ShowGayImage',
        'So hilarious to see you like this @ShowGayImage',
        'Don\'t mind me %EmoteOther% @ShowGayImage',
        'There\'s no shortage of pictures to tease you with, that\'s for sure @ShowGayImage',
        '%Grin% @ShowGayImage',
        'You look almost exactly like them @ShowGayImage',
        'Soon you will be a part of this... @ShowGayImage',
        'Imagine blowing their cock... @ShowGayImage',
        'I want you to remember this for a long time %SlaveName%',
        'You are so fucking sexy to me right now',
        'You are going to blow until you forget your name',
        'I want this to be torture for you %SlaveName%',
        'There is nothing else I\'d rather be doing than making you suffer %EmoteOther%',
        'Make that cock feel as good as you possibly can',
        'Imagine blowing a real dick %Lol%',
        'Blow that cock gently',
        'Just imagine what I would be doing to you right now if I was there with you %Grin%',
        'I\'m loving every second of this %EmoteOther%',
        'You were made to suffer for me %SlaveName%',
        'I haven\'t even begun to fuck with you yet %SlaveName% %EmoteOther%',
        'I\'m gonna make sure that throat remembers every single deepthroat you give to me %Grin%',
        'Don\'t stop blowing, %SlaveName%',
        'Keep blowing, %SlaveName%',
        'Keep blowing',
        'Don\'t stop blowing',
        'I want you to keep blowing',
        'Keep going, %SlaveName%',
        'Keep blowing just like that',
        'Keep blowing for me',
        'Just keep blowing',
        'Keep it just like that, %SlaveName%',
        'You\'re doing great, keep going %Grin%',
        'Keep going, you don\'t deserve any mercy, %SlaveName%',
        'Don\'t stop, just blow blow blow %Grin%',
        'Keep blow-blow-blowing, %SlaveName% %Grin%',
        'Don\'t stop, blow',
        'Don\'t slow dow, keep blowing just like that',
        'You need to keep blowing that dildo',
        'Keep blowing my toy, %SlaveName%',
        'Don\'t stop blowing that dildo',
        'Keep blowing that dildo',
        'Keep it up, it\'s not time to stop yet',
        'Be as fast as you possibly can @StrokeFastest',
        'Go fast %SlaveName%, I want your head to be a blur @StrokeFastest',
        'Gotta go fast! @StrokeFastest',
        'Gotta go fast! %Lol% @StrokeFastest',
        'Slow it down a little bit @StrokeSlower',
        'A little slower for me @StrokeSlower',
        'Slow down your pace a little bit @StrokeSlower',
        'I want you to slow down a little bit more @StrokeSlower',
        'Slow down a little @StrokeSlower',
        'Slower @StrokeSlower',
        'Slower %SlaveName% @StrokeSlower',
        'Slow down a little more @StrokeSlower',
        'Speed it up a little bit @StrokeFaster',
        'A little faster for me @StrokeFaster',
        'Speed up your pace a little bit @StrokeFaster',
        'I want you to speed up even more @StrokeFaster',
        'Speed up a little, I want this to be hard on you %Grin% @StrokeFaster',
        'Faster, I want you to suffer %EmoteHappy% @StrokeFaster',
        'Faster @StrokeFaster',
        'Faster %SlaveName% @StrokeFaster',
        'Speed up a little @StrokeFaster',
        'I want you to be as slow as possible @StrokeSlowest',
        'Slow it all the way down %SlaveName%, make it frustrating @StrokeSlowest',
        'Now slow way down @StrokeSlowest',
    ];

    let answer = findRandomUnusedElement(answers, createHistory('basicBlowingTaunt'));

    interpretLegacyTaunt(answer, LEGACY_TAUNT_TYPE_ORAL);
}