const STROKE_AND_TEASE_TAUNTS = [
    'Make it feel good %SlaveName%',
    'Make %MyCock% %Cock% feel ' + random('amazing', 'good'),
    'Tease tease tease %Grin%',
    'Drip drip drip %Giggles%',
    'Just suffer ' + random('for me', '') + ' %SlaveNameSmiley%',
    'Keep suffering %SlaveNameSmiley%',
    'Keep going %SlaveNameSmiley%',
    'Keep %TeaseVerb% just like that... Good %SlaveNameSmiley%',
    'Don\'t stop %TeaseVerb%',
    'Don\'t stop %SlaveName%, I want you even ' + 'more aroused',
    'Don\'t stop %SlaveName%, I want %MyYour% %Cock% try to get even ' + 'harder',
    'I know you can keep going for me, %SlaveName%',
    'You have no choice but to keep %TeaseVerb% for me',
    'When I see a pair of %Boobs% like that, I just want to grab them %EmoteHappy% @ShowBoobsImage',
    'I love that you\'re doing this for me',
    'I love how much you\'re willing to make yourself ache for me',
    'It turns me on so much that you do this for me',
    'I\'m loving every second of this %Grin%',
    random('I love making you ', 'Nothing gets me hotter than making you ') + random('do this', 'suffer', 'drip', 'ache') + ' for me',
    'It turns me on so much when you suffer for me',
    'Your suffering turns me on so much',
    'You have no idea how much I ' + random('enjoy', 'love') + ' seeing you suffer for me',
    'It makes me ' + random('wet', 'hot') + ' to know you\'d do anything for me, %SlaveName%',
    'I wish I could see you right now',
    'I\'m trying to picture you sitting there all flushed and sweaty %EmoteHappy%',
    'I want you more ' + random('aroused', 'turned on', 'horny') + ' than you\'ve ever been in your entire life',
    'I want you aching',
    'I want you suffering',
    'I want you to ache like never before',
    'Suffer for me',
    'Making you ache makes me feel so good',
    'I\'m gonna take all your pleasure for myself',
    'I\'m gonna take every last bit of your pleasure for myself',
    'Show me how much you want to please me',
    'Make yourself ache for my ' + random('enjoyment', 'pleasure'),
    'Ache for me',
    'Keep aching for me',
    'Let every second make you ' + random('ache for me even more', 'even more desperate'),
    'Just switch off you brain and suffer now',
    'I\'m going to make this so much worse on you',
    'That ache isn\'t going to get any easier',
    'Mmmm @ShowBlogImage',
    'Sexy @ShowBlogImage',
    'Nice @ShowBlogImage',
    'That\'s sexy @ShowBlogImage',
    'That\'s hot @ShowBlogImage',
    'So hot @ShowBlogImage',
    'The internet is just an endless supply of hotness %EmoteHappy% @ShowBlogImage',
    'Don\'t mind me %EmoteOther% @ShowBlogImage',
    'There\'s no shortage of pictures to tease you with, that\'s for sure @ShowBlogImage',
    'I could just scroll through these porn blogs all day and never get bored @ShowBlogImage',
    '%Moan% @ShowBlogImage',
    'Mmm good stuff... @ShowBlogImage',
    'This is nice... @ShowLocalImage',
    'I want you to remember this ache for a long time %SlaveName%',
    'You are so fucking sexy to me right now',
    'You are going to ache until you forget your name',
    'I want this to be torture for you %SlaveName%',
    'There is nothing else I\'d rather be doing than making you suffer %EmoteOther%',
    'I\'m going to ' + random('fuck you up so bad', 'drive you crazy') + ' %Lol%',
    'I\'m going to drive you completely insane %EmoteOther%',
    'I want you so fucking desperate %SlaveName%',
    'I want %MyYour% %Cock% to leak drops of desperation',
    'You are going to give me whatever I want, %SlaveName%',
    'Just imagine what my fingers would be doing to you right now %Grin%',
    'I\'m loving every second of this %EmoteOther%',
    'You were made to suffer for me %SlaveName%',
    'I haven\'t even begun to fuck with you yet %SlaveName% %EmoteOther%',
    'I\'m gonna make sure %MyCock% %Cock% remembers every single second %Grin%',
    'Don\'t stop, %SlaveName%',
    'Keep teasing, %SlaveName%',
    'Keep teasing',
    'Don\'t stop teasing',
    'I want you to keep teasing',
    'Keep going, %SlaveName%',
    'Keep teasing just like that ',
    'Keep teasing for me',
    'Just keep teasing',
    'You need to keep teasing %MyCock% %Cock%',
    'Keep teasing my toy, %SlaveName%',
    'Don\'t stop teasing %MyCock% %Cock%',
    'Keep teasing %MyCock% %Cock%',
    'Keep going just like that, %SlaveName%',
    'You\'re doing great, keep going %Grin%',
    'Keep going, you don\'t deserve any mercy, %SlaveName%',
    'Don\'t stop, just suffer %Grin%',
    'Keep %TeaseVerb%, %SlaveName% %Grin%',
    'Don\'t stop, ' + random('tease', 'suffer', 'ache'),
    'Don\'t back off, keep going just like that',
    'Keep it up, it\'s not time to stop %TeaseVerb% yet'
];

function getTeaseVerb() {
    return random('suffering', 'dripping', 'teasing', 'aching');
}